# Uses https://github.com/pascalgn/automerge-action

name: Auto-merge
on: 
  pull_request:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps: 
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          LOG: DEBUG
